sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc    

after_success:      
  - rm -f Gemfile.lock
  - bundle config --local github.https true
  - bundle --path=.bundle/gems --binstubs=.bundle/.bin
  
  
  
  
  - ls ;
  - cp -b codereview.gif output;
  - cd output ;
  - ls ;
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
 
